type TextItem @embedded {
  title: String!
  description: String!
  content: String!
  citation: String
}


enum MediaFormat {
  IMAGE
  AUDIO
  VIDEO
  DOCUMENT
}


type MediaItem @embedded {
  format: MediaFormat!
  title: String!
  description: String!
  url: String!
  citation: String
}


type Place @embedded {
  country: String!
  region: String
  locale: String
}


type Birth @embedded {
  date: Date
  place: Place
}


type Death @embedded {
  date: Date
  place: Place
}


enum Gender {
  MALE
  FEMALE
  NONBINARY
}


type Person {
  familyName: String
  givenName: String
  middleNames: [String!]
  legalSurnames: [String!]
  professionalName: String
  alsoCreditedAs: [String!]
  birth: Birth
  death: Death
  gender: Gender
  notes: String
  wikipediaUrl: String
  textItems: [TextItem!]
  mediaItems: [MediaItem!]
  memberOf: [Artist!] @relation
}


type Artist {
  name: String!
  dahrTalentId: ID
  discogsArtistId: ID
  spotifyArtistId: ID
  wikipediaUrl: String
  textItems: [TextItem!]
  mediaItems: [MediaItem!]
  members: [Person!] @relation
  recordings: [Recording!] @relation
  releases: [Release!] @relation
  tracks: [Track!] @relation
}


enum SongRole {
  WRITER
  COMPOSER
  LYRICIST
  ARRANGER
  TRANSCRIBER
  COLLECTOR
  PUBLISHER
}


type SongCredit {
  person: Person!
  role: SongRole!
  songs: [Song!] @relation
}


type Song {
  roudNum: String
  childNum: String
  otherNums: [String!]
  canonicalName: String
  versionName: String
  tuneName: String
  otherNames: [String!]
  citation: String
  notes: String
  wikipediaUrl: String
  textItems: [TextItem!]
  mediaItems: [MediaItem!]
  credits: [SongCredit!] @relation
  relatedSongs: [Song!]
}


enum SessionType {
  COMMERCIAL
  DOCUMENTARY
  AMATEUR
}


enum SessionRole {
  PRODUCER
  SUPERVISOR
  TECHNICAL
  COLLECTOR
  ASSISTANT
  SELF_RECORDING
}


type SessionCredit {
  person: Person!
  role: SessionRole!
  recordings: [Recording!] @relation
}


enum PerformerRole {
  VOCALIST
  INSTRUMENTALIST
  SPEAKER
}


type PerformerCredit {
  person: Person!
  role: PerformerRole
  details: String
  dahrTalentId: ID
  recordings: [Recording!] @relation
}


type Recording {
  song: Song
  artists: [Artist!] @relation
  primaryTitle: String
  alternateTitles: [String!]
  date: Date
  place: Place
  type: SessionType
  organization: String
  catalogNum: String
  sessionCredits: [SessionCredit!] @relation
  performerCredits: [PerformerCredit!] @relation
  takeNumber: Int
  isMaster: Boolean
  notes: String
  dahrMatrixId: ID
  textItems: [TextItem!]
  mediaItems: [MediaItem!]
}


type Release {
  date: Date
  country: String
  artists: [Artist!] @relation
  primaryTitle: String
  alternateTitles: [String!]
  label: String
  catalogNum: String
  format: String
  isCompilation: Boolean
  isReissue: Boolean
  notes: String
  discogsReleaseId: ID
  discogsMasterId: ID
  spotifyAlbumId: ID
  tidalAlbumId: ID
  textItems: [TextItem!]
  mediaItems: [MediaItem!]
}


type AudioFeatures @embedded {
  durationMs: Int
  key: Int
  mode: Int
  timeSignature: Int
  acousticness: Float
  danceability: Float
  energy: Float
  instrumentalness: Float
  liveness: Float
  loudness: Float
  speechiness: Float
  valence: Float
  tempo: Float
}


type Track {
  recording: Recording
  release: Release
  artists: [Artist!] @relation
  title: String
  position: String
  notes: String
  spotifyTrackId: ID
  tidalTrackId: ID
  audioFeatures: AudioFeatures
  textItems: [TextItem!]
  mediaItems: [MediaItem!]
}


type Query {
  allSongs: [Song!]
  allArtists: [Artist!]
  allRecordings: [Recording!]
  allReleases: [Release!]
  allTracks: [Track!]
}
