type TextItem {
  title: String!
  description: String!
  content: String!
  citation: String
}


enum MediaFormat {
  IMAGE
  AUDIO
  VIDEO
}


type MediaItem {
  title: String!
  description: String!
  format: MediaFormat!
  url: String! @unique
  citation: String
}


type Place {
  country: String!
  region: String
  locale: String
}


enum Gender {
  MALE
  FEMALE
  NONBINARY
}


type Person {
  lastName: String
  firstName: String
  otherNames: [String!]
  gender: Gender 
  birthDate: Date
  birthPlace: Place
  deathDate: Date
  deathPlace: Place
  notes: String
  memberOf: [Artist!] @relation
}


type Artist {
  name: String!
  members: [Person!] @relation
}


enum SongRole {
  WRITER
  COMPOSER
  LYRICIST
  ARRANGER
  TRANSCRIBER
  COLLECTOR
  PUBLISHER
}


type SongCredit {
  name: Person!
  role: SongRole!
}


type Song {
  roudNum: String
  childNum: String
  otherNums: [String!]
  canonicalName: String
  versionName: String
  tuneName: String
  otherNames: [String!]
  credits: [SongCredit!]
  citation: String
  notes: String
  textItems: [TextItem!]
  mediaItems: [MediaItem!]
}


enum SessionType {
  COMMERCIAL
  DOCUMENTARY
  AMATEUR
}


type SessionCredit {
  name: Person!
  role: String!
}


type Session {
  type: SessionType
  date: Date
  place: Place
  credits: [SessionCredit!]
  organization: String
  notes: String
}


enum PerformerRole {
  VOCALIST
  INSTRUMENTALIST
  SPEAKER
}


type PerformerCredit {
  name: Person!
  role: PerformerRole
  details: String
}


type Recording {
  identifier: String
  session: Session
  song: Song
  primaryTitle: String
  alternateTitles: [String!]
  artists: [Artist!] @relation
  credits: [PerformerCredit!] @relation
  takeNumber: Int
  isMaster: Boolean
  notes: String
  textItems: [TextItem!] @relation
  mediaItems: [MediaItem!] @relation
}


type Release {
  label: String
  catalogNum: String
  date: Date
  country: String
  format: String
  primaryTitle: String
  alternateTitles: [String!]
  artists: [Artist!] @relation
  isCompilation: Boolean
  isReissue: Boolean
  notes: String
  textItems: [TextItem!] @relation
  mediaItems: [MediaItem!] @relation
  discogsUrl: String
  spotifyUrl: String
  tidalUrl: String
}


type Track {
  recording: Recording
  release: Release
  title: String
  position: String
  artists: [Artist!] @relation
  notes: String
  textItems: [TextItem!] @relation
  mediaItems: [MediaItem!] @relation
}


type Query {
  allSongs: [Song!]
  allArtists: [Artist!]
  allRecordings: [Recording!]
  allReleases: [Release!]
  allTracks: [Track!]
}
