# Song
canonicalName = "Identifies a set of variations on a traditional theme"
versionName = "Identifies a specific variation of a traditional theme"
tuneName = "Alternative name for the tune associated with this variation"
otherNames = ["Alternative names by which the theme/version is known"]
roudNum = "Number assigned in the Roud Folk Song Index (if any)"
childNum = "Number assigned in the Child Ballads (if any)"
otherNums = ["Identifiers used in other collections"]
credits = ["Creator/contributor credits listed as ROLE: NAME"]
notes = "Information relevant to further research"

[[transcriptions]]
title = "Title of the song/tune as printed in the collection"
credits = ["Listed as ROLE: NAME AS CREDITED (MORE COMMON NAME)"]
pageNumber = "Page number where the title appears"
url = "Direct URL for the digitized transcription"
[transcriptions.publication]
  title = "Title of the published collection"
  credits = ["Listed as ROLE: NAME AS CREDITED (MORE COMMON NAME)"]
  edition = "If not first edition, provide edition number"
  publisher = "Publication company, imprint name, or institutional publisher"
  place = "Formatted as CITY (COUNTRY)"
  year = "Original publication year for edition (ignoring reprints)"
  vol = "Volume number for multi-volume publications"
  issue = "Issue number or other identifier for serial publications"
  catalogRef = "Reference in a library catalog or archival system"
  url = "URL for digitized source, library record, or purchasing info"

[[recordings]]
title = "Title of the released track or audio file of a recording"
artists = "[Solo artist name, group name, or multiple performers/groups]"
sessionType = "COMMERCIAL|DOCUMENTARY|AMATEUR"
date = "Date of the recording session as YEAR (MONTH DAY)"
place = "Place of the recording session as CITY, STATE (COUNTRY)"
personnel = ["Listed as ROLE: NAME AS CREDITED (MORE COMMON NAME)"]
matrixNum = "Matrix number as etched on the A or B side of a single"
isMaster = "TRUE|FALSE (if one of multiple takes)"
takeNum = "Take number as documented (if one of multiple takes)"
dahrID = "Matrix ID in UCSB's Discography of American Historical Recordings"
catalogRef = "Reference in a library catalog or archival system"
url = "URL for additional details about the recording"
[recordings.release]
  title = "Title of the original release on which the track appears"
  year = "Year of the original release (ignoring reissues)"
  label = "Label of the original release formatted as NAME (COUNTRY)"
  matrixNum = "Matrix number(s) as etched on an LP or CD"
  catalogNum = "Catalog number as printed on the label of a record or CD"
  discogsId = "Release ID on Discogs"
  url = "URL for additional details about the original release"
[recordings.compilation]
  title = "Title of a compilation on which the track appears"
  year = "Year of the compilation release (ignoring reissues)"
  label = "Label of the compilation release"
  discogsId = "Release ID on Discogs"
  url = "URL for additional details about the compilation release"
[recordings.streaming]
  spotifyId = "Track ID on Spotify"
  tidalId = "Track ID on TIDAL"
  youtubeId = "Video ID on YouTube"
  archiveId = "Item ID on Internet Archive"

[[arrangements]]
format = "ABC|VEXTAB|IMAGE"
instruments = "Instruments included in this arrangement"
tonic = "The tonal center of the arrangement (often the final/resting tone)"
mode = "Best classification of the pitch set relative to the tonal center"
content = "Notation to render or URL of image"
source = "Source citation for arrangement (may reference transcription)"

[[media]]
format = "IMAGE|AUDIO|VIDEO|WEBSITE|PDF"
url = "URL to view or download"
title = "Title of the media item"
description = "Brief description of the contents"
citation = "Full source citation as appropriate"
